"""Initial CD catalogue, kept in the order supplied by the owner."""

CD_SEED = [
    ("The Low End Theory", "A Tribe called quest", True),
    ("To pimp a butterfly", "Kendrick Lamar", True),
    ("dummy", "Portishead", True),
    ("Mezzanine", "Massive Attack", True),
    ("rodeo", "Travis scott", True),
    ("debut", "The xx", True),
    ("Nonagon Infinity", "King Gizzard and the Lizard Wizard", True),
    ("Funeral", "Arcade Fire", True),
    ("The college dropout", "Kanye West", True),
    ("Remain in Light", "Talking Heads", True),
    ("Atom Heart Mother", "Pink Floyd", True),
    ("Ok Computer", "Radiohead", True),
    ("good kid baad city", "Kendrick lamar", True),
    ("Aquemini", "Outkast", True),
    ("Discovery", "Daft Punk", True),
    ("Rain Dogs", "Tom Waits", True),
    ("Me Against the world", "2pac", True),
    ("The money store", "Death Grips", True),
    ("Ilmatic", "Nas", True),
    ("Beloved! Paradise! Jazz!?", "Mckinley Dixon", True),
    ("Blackstar", "David Bowie", True),
    ("Safizam", "SAF", True),
    ("Enter the 36 chambers", "Wu-Tang", True),
    ("Is this it?", "The Strokes", True),
    ("plowing in the field of love", "Iceage", True),
    ("IGOR", "Tyler, the creator", True),
    ("Fear of Music", "Talking Heads", True),
    ("Yankee foxtrot Hotel", "Wilco", True),
    ("redstar wu and the worldwide scourge", "Genesis Owusu", True),
    ("We Got it from here… Thank you 4 your service", "A Tribe called quest", True),
    ("What's your pleasure?", "Jessie Ware", True),
    ("4eva is a mighty long time", "Big KRIT", True),
    ("Room on fire", "The Strokes", False),
    ("The new abnormal", "The Strokes", False),
    ("Samurai", "Lupe Fiasco", False),
    ("Imaginal Disc", "Magdalena Bay", False),
    ("Ants from up here", "Black Country, New Road", False),
    ("LL", "The hellp", False),
    ("..Like clockwork", "Queens of the stone age", False),
    ("Lift your skinny fists up like antennas to Heaven", "Godspeed You! Black Emperor!", False),
    ("45:33", "LCD Soundsystem", False),
    ("Sound of Silver", "LCD Soundsystem", False),
    ("This is Happening", "LCD Soundsystem", False),
    ("hiding places", "Billy woods", False),
    ("maps", "Billy woods", False),
    ("Midnight Marauders", "A Tribe called quest", False),
    ("1999", "Joey Bada$$", False),
    ("Blonde", "Frank Ocean", False),
    ("All my heroes are cornballs", "JPEGMAFIA", False),
    ("i lay down my life for you", "JPEGMAFIA", False),
    ("donuts", "J Dilla", False),
    ("Atrocity Exhibition", "Danny Brown", False),
    ("Scaring the hoes", "Danny Brown, JPEGMAFIA", False),
    ("Black on both sides", "Mos Def", False),
    ("Unknown Pleasures", "Joy Division", False),
    ("Deltron 3030", "Deltron 3030", False),
    ("Die lit", "Playboi Carti", False),
    ("Entroducing….", "Dj Shadow", False),
    ("F#A# infinity", "Godspeed You! Black Emperor!", False),
    ("Speaking in Tongues", "Talking Heads", False),
    ("Flying Microtonal Banana", "King Gizzard and the Lizard Wizard", False),
    ("The Suburbs", "Arcade Fire", False),
    ("Ziggy Stardust", "David Bowie", False),
    ("Saturation 2", "Brockhampton", False),
    ("Since I left you", "The Avalanches", False),
    ("Vtora mladost, treta svetska vojna", "Bernays Propaganda", False),
    ("By the time I get to phoenix", "Injury Reserve", False),
    ("Carrie and Lowell", "Sufjan Stevens", False),
    ("below the heavens", "Blu&exile", False),
    ("cave world", "Viagra boys", False),
]
